In [112]:
#Jaydatt Patel 202201268

In [113]:
import requests
with open("hill_cipher_extra_credit.py", 'w') as foo:
    foo.write(requests.get("https://git.io/JenzP").text)
with open("hill_cipher_extra_credit_samples.py", 'w') as foo:
    foo.write(requests.get("https://git.io/JenzX").text)
from hill_cipher_extra_credit import *

In [114]:
char2num("ABCDEF")

[1, 2, 3, 4, 5, 6]

In [115]:
mylist = [20,8,9,19,0,9,19,0,1,0,20,5,19,20, 100, -1]
num2char(mylist)

  20   8   9  19   0   9  19   0   1   0  20   5  19  20 100  -1
   T   H   I   S   _   I   S   _   A   _   T   E   S   T   #   #



In [116]:
mylist = [20,8,9,19,0,9,19,0,1,0,20,5,19,20, 100, -1]
num2char_text_only(mylist)

'THIS_IS_A_TEST##'

In [117]:
pnum = 202201268

In [118]:
cipher = cipher_generator(pnum)
cipher

[194, 18, 243, 115, 15, 144, 245, 19, 309, 152, 10, 195, 150, 23, 183, 83, 4, 
105, 42, 5, 54, 238, 19, 306, 177, 26, 219, 105, 14, 135, 294, 19, 378, 119, 5
, 153, 235, 34, 294, 5, 1, 6, 195, 24, 243, 133, 19, 165]

In [119]:
partial_decryption = "CONFIDENTIAL"
partial_num_d = char2num(partial_decryption)
partial_num_d

[3, 15, 14, 6, 9, 4, 5, 14, 20, 9, 1, 12]

In [120]:
v01 = Matrix(partial_num_d[:3])
v02 = Matrix(partial_num_d[3:6])
v03 = Matrix(partial_num_d[6:9])
v04 = Matrix(partial_num_d[9:12])
v01, v02, v03, v04

⎛⎡3 ⎤  ⎡6⎤  ⎡5 ⎤  ⎡9 ⎤⎞
⎜⎢  ⎥  ⎢ ⎥  ⎢  ⎥  ⎢  ⎥⎟
⎜⎢15⎥, ⎢9⎥, ⎢14⎥, ⎢1 ⎥⎟
⎜⎢  ⎥  ⎢ ⎥  ⎢  ⎥  ⎢  ⎥⎟
⎝⎣14⎦  ⎣4⎦  ⎣20⎦  ⎣12⎦⎠

So we have followinf 4 equations :
D*w1 = v1 , D*w2 = v2 , D*w3 = v3 , D*w4 = v4 
where D is our decryption key matrix
D * [w1 w2 w3] = [v1 v2 v3] 
D = [v1 v2 v3]*(inv of [w1 w2 w3])
so below this code i have find the inverse of matrix A i.e [w1 w2 w3]

In [156]:
import numpy as np
 

A = np.array([[194, 18, 243],
              [115, 15, 144],
              [245, 19, 309]])

def transpose_matrix(A):
    return [[A[j][i] for j in range(len(A))] for i in range(len(A[0]))]

transposed_matrix = transpose_matrix(A)

for row in transposed_matrix:
    print(row)

print()
B = np.linalg.inv(transposed_matrix)

print(B)

[194, 115, 245]
[18, 15, 19]
[243, 144, 309]

[[ 1.08762887 -0.14604811 -0.85337915]
 [-0.54123711  0.23539519  0.41466208]
 [-0.60309278  0.00515464  0.48109966]]


after finding inverse , now we have to multiply that matrix B with [v1 v2 v3] i.e matrix C

In [161]:
C = ([[3, 6, 5],
      [15, 9, 14],
      [14, 4, 20]])

Q = [[0, 0, 0],
     [0, 0, 0],
     [0, 0, 0]]

for i in range(len(A)):
    for j in range(len(B[0])):
        for k in range(len(B)):
            Q[i][j] += C[i][k] * B[k][j]

for row in Q:
    print(row)

[-2.9999999999999867, 1.0000000000000009, 2.3333333333333224]
[2.9999999999999822, -7.355227538141662e-16, -2.3333333333333206]
[0.9999999999999982, -1.0000000000000004, -0.6666666666666661]


after multiplication we have to do modulo with 27 to get accuracte answer  

In [143]:
fkey = [[elem % 27 for elem in row] for row in Q]
print(fkey)

[[24.000000000000014, 1.0000000000000009, 2.3333333333333224], [2.9999999999999822, 27.0, 24.66666666666668], [0.9999999999999982, 26.0, 26.333333333333336]]


Now as we got the decryption key , we have to find what the sentence that numbers that are generated by my studentid gives us 
so we multiply all the numbers with the decryption key in 3x1 vector manner and then combine all that vector in one sequence using "np.vstack" function

In [162]:

decryption_key = [[24.000000000000014, 1.0000000000000009, 2.3333333333333224], 
      [2.9999999999999822, 27.0, 24.66666666666668], 
      [0.9999999999999982, 26.0, 26.333333333333336]]

vectors = [
    np.array([[194], [18], [243]]),
    np.array([[115], [15], [144]]),
    np.array([[245], [19], [309]]),
    np.array([[152], [10], [195]]),
    np.array([[150], [23], [183]]),
    np.array([[83], [4], [105]]),
    np.array([[42], [5], [54]]),
    np.array([[238], [19], [306]]),
    np.array([[177], [26], [219]]),
    np.array([[105], [14], [135]]),
    np.array([[294], [19], [378]]),
    np.array([[119], [5], [153]]),
    np.array([[235], [34], [294]]),
    np.array([[5], [1], [6]]),
    np.array([[195], [24], [243]]),
    np.array([[133], [19], [165]])
]

results = []

for v in vectors:
    result = np.dot(decryption_key, v)
    results.append(result)

all_results = np.vstack(results)

arr = np.array(all_results)
output_sequence = arr.reshape(1, -1)

print(output_sequence)


[[ 5241.  7062.  7061.  3111.  4302.  4297.  6620.  8870.  8876.  4113.
   5536.  5547.  4050.  5585.  5567.  2241.  2947.  2952.  1139.  1593.
   1594.  6445.  8775.  8790.  4785.  6635.  6620.  2849.  4023.  4024.
   7957. 10719. 10742.  3218.  4266.  4278.  6360.  8875.  8861.   135.
    190.   189.  5271.  7227.  7218.  3596.  4982.  4972.]]


now lets represnts this output in proper form so that we can convert this sequence in sentance that we want

In [152]:
S = [ 5241,  7062,  7061,  3111,  4302,  4297,  6620,  8870,  8876,  4113,  5536,  5547,  4050,  5585,  5567,  2241,  2947,  2952,  1139,  1593, 1594,  6445,  8775,  8790,  4785,  6635,  6620,  2849,  4023,  4024,  7957, 10719, 10742,  3218,  4266,  4278,  6360,  8875,  8861,   135,  190,   189,  5271,  7227,  7218,  3596,  4982, 4972]


now as we have our final sequence but as we know alphabets are assigned from 1-26 i.e. A=0,B=1,C=3 and so no upto Z=26 and sapce = 0
so we have to modolo this sequence with 27 

In [153]:
Final_codeword = [elem % 27 for elem in S]

print(Final_codeword)

[3, 15, 14, 6, 9, 4, 5, 14, 20, 9, 1, 12, 0, 23, 5, 0, 4, 9, 5, 0, 1, 19, 0, 15, 6, 20, 5, 14, 0, 1, 19, 0, 23, 5, 0, 12, 15, 19, 5, 0, 1, 0, 6, 18, 9, 5, 14, 4]


now as we got all the numbers of sequence between 0 to 27 now lets call num2char function to convert this sequence in our final sentance 

In [154]:
num2char(Final_codeword)

   3  15  14   6   9   4   5  14  20   9   1  12   0  23   5   0   4   9   5   0
   C   O   N   F   I   D   E   N   T   I   A   L   _   W   E   _   D   I   E   _

   1  19   0  15   6  20   5  14   0   1  19   0  23   5   0  12  15  19   5   0
   A   S   _   O   F   T   E   N   _   A   S   _   W   E   _   L   O   S   E   _

   1   0   6  18   9   5  14   4
   A   _   F   R   I   E   N   D



ans its done our final qoute is 

My answer = CONFIDENTIAL WE DIE AS OFEN AS WE LOSE A FRIEND 